This notebook cleans the data retrieved from KB long-term-stable data set versions. Duplicates are removed and the data is saved in a new file. The item_ids are saved for the future reference retrieval. In a following notebook, the data is preliminarily analyzed and visualized.

In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns
#import re
#import numpy as np
#import matplotlib as mpl

# Fonts for plots
#mpl.rcParams['font.serif'] = 'Times New Roman'
#plt.rcParams['font.family'] = 'serif'

#pd.set_option('display.max_columns', None)

# Path to data retrieval and storage
path = "C:/Users/kleinow/ownCloud/MA_Neuro"

In [2]:
# Load KB data; 12 data frames
# cn1 indicates "computational neuroscience", whereas cn2 indicates "computational neurosciences" (note the -s)

# CompNeuro found in keyword section 
cn1 = pd.read_csv(path + '/cn1.csv')
cn2 = pd.read_csv(path + '/cn2.csv')

#CompNeuro found in title section
cn1_t = pd.read_csv(path + '/cn1_titles.csv')
cn2_t = pd.read_csv(path + '/cn2_titles.csv')

#CompNeuro found in abstract section
cn1_abs = pd.read_csv(path + '/cn1_abs.csv')
cn2_abs = pd.read_csv(path + '/cn2_abs.csv')

# Corresponding abstract retrieval for each of the data frames above
cn1_abstracts = pd.read_csv(path + '/cn1_abstracts.csv')
cn2_abstracts = pd.read_csv(path + '/cn2_abstracts.csv')
cn1_t_abstracts = pd.read_csv(path + '/cn1_titles_abstracts.csv')
cn2_t_abstracts = pd.read_csv(path + '/cn2_titles_abstracts.csv')
cn1_abs_abstracts = pd.read_csv(path + '/cn1_abs_abstracts.csv')
cn2_abs_abstracts = pd.read_csv(path + '/cn2_abs_abstracts.csv')



In [3]:
# Merge abstracts to data frames
# Attention: Contrary to the KB overview, the abstract column is called "abstract" here, not "abstract_text"
cn1 = cn1.merge(cn1_abstracts[['item_id', 'abstract']], on='item_id', how='left')
cn2 = cn2.merge(cn2_abstracts[['item_id', 'abstract']], on='item_id', how='left')

cn1_t = cn1_t.merge(cn1_t_abstracts[['item_id', 'abstract']], on='item_id', how='left')
cn2_t = cn2_t.merge(cn2_t_abstracts[['item_id', 'abstract']], on='item_id', how='left')

cn1_abs = cn1_abs.merge(cn1_abs_abstracts[['item_id', 'abstract']], on='item_id', how='left')
cn2_abs = cn2_abs.merge(cn2_abs_abstracts[['item_id', 'abstract']], on='item_id', how='left')

In [4]:
# Append the cn2 data frames to the cn1 data frames and remove occuring duplicates
cn = cn1.append(cn2).drop_duplicates().reset_index(drop=True) # method chaining
cn_t = cn1_t.append(cn2_t).drop_duplicates().reset_index(drop=True)
cn_abs = cn1_abs.append(cn2_abs).drop_duplicates().reset_index(drop=True)

# Comparison of the length of the data frames
lengths = {
    "DataFrame": ["cn1", "cn2", "cn_combined", "cn1_t", "cn2_t", "cn_t_combined", "cn1_abs", "cn2_abs", "cn_abs_combined"],
    "Length": [
        len(cn1), len(cn2), len(cn),
        len(cn1_t), len(cn2_t), len(cn_t),
        len(cn1_abs), len(cn2_abs), len(cn_abs)
    ]
}

length_df = pd.DataFrame(lengths)
length_df


C:\Users\kleinow\AppData\Local\Temp\ipykernel_14808\2455577134.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cn = cn1.append(cn2).drop_duplicates().reset_index(drop=True) # method chaining
C:\Users\kleinow\AppData\Local\Temp\ipykernel_14808\2455577134.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cn_t = cn1_t.append(cn2_t).drop_duplicates().reset_index(drop=True)
C:\Users\kleinow\AppData\Local\Temp\ipykernel_14808\2455577134.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cn_abs = cn1_abs.append(cn2_abs).drop_duplicates().reset_index(drop=True)


DataFrame  Length
0              cn1     705
1              cn2      11
2      cn_combined     716
3            cn1_t      72
4            cn2_t       0
5    cn_t_combined      72
6          cn1_abs     903
7          cn2_abs      22
8  cn_abs_combined     924

Note: There were entirely no finds for "computational neurosciences" in the title section of the KB search results.

In [5]:
# Merge the results for keyword section, title, and abstract
cn_full = cn.append([cn_t, cn_abs]).drop_duplicates().reset_index(drop=True)
cn_full.shape # (1587, 51)

C:\Users\kleinow\AppData\Local\Temp\ipykernel_14808\3540281187.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cn_full = cn.append([cn_t, cn_abs]).drop_duplicates().reset_index(drop=True)


(1587, 51)

By merging the results for the keyword section, title and abstract, we get a data frame with 1587 entries. During the merging process, 125 publications have been removed from the otherwise combined 1712 publications.

In [6]:
# Add a column with the title in lower case
cn_full['title_lower'] = cn_full['item_title'].str.lower()
cn_full.title_lower.nunique() # only 1552 unique titles

duplicated_mask = cn_full['title_lower'].duplicated(keep=False) # keep = False marks all duplicates as True, not just the subsequent ones after the first occurrence

non_unique = cn_full[duplicated_mask]
non_unique # shows all the duplicated titles

item_id fk_repository_history pubyear  pubmonth  \
32    WOS:000389557000015              52378983    2016      10.0   
177   WOS:000184147100024              33473482    2003       NaN   
215   WOS:000376684300020               7930336    2015       NaN   
265   WOS:000264956700003              20687095    2009       3.0   
277   WOS:000339937700001              73952925    2014       6.0   
...                   ...                   ...     ...       ...   
1582  WOS:000166212100001              32739148    2000      10.0   
1583  WOS:000894965000001              70541596    2022      11.0   
1584  WOS:000321898300005               6794670    2013       8.0   
1585  WOS:000392212200010               1259555    2010       NaN   
1586  WOS:000377962500055              53506649    2016       5.0   

     wos_pubdate_online                                         item_title  \
32                  NaN  Correlation between videogame mechanics and ex...   
177                 NaN  Noise in a randomly and sparsely connected exc...   
215                 NaN  Can Videogames Improve Executive Functioning? ...   
265                 NaN  Cortical basis of communication: Local computa...   
277                 NaN  Toward a new cognitive neuroscience: modeling ...   
...                 ...                                                ...   
1582                NaN  Reorganization of the human CNS - Neurophysiol...   
1583                NaN  Virtual Intelligence: A Systematic Review of t...   
1584                NaN  Action, Outcome, and Value: A Dual-System Fram...   
1585                NaN  Grid-wide neuroimaging data federation in the ...   
1586                NaN  A subsequent closed-form description of propag...   

     scopus_item_title_non_eng                     first_author  \
32                         NaN                  Mondejar, Tania   
177                        NaN                       Vibert, JF   
215                        NaN                  Mondejar, Tania   
265                        NaN              Alexandre, Frederic   
277                        NaN                   Gramann, Klaus   
...                        ...                              ...   
1582                       NaN                       Schalow, G   
1583                       NaN  Zavala Hernandez, Jesus Gerardo   
1584                       NaN                   Cushman, Fiery   
1585                       NaN                   Michel, Franck   
1586                       NaN              Melendy, Robert. F.   

                                doi        pmid  ... fncr_5_years  \
32        10.1016/j.jbi.2016.08.006  27507089.0  ...     1.939175   
177               10.1117/12.488736         NaN  ...     0.000000   
215    10.1007/978-3-319-26508-7_20         NaN  ...     0.000000   
265    10.1016/j.neunet.2009.01.006  19217253.0  ...     0.163626   
277        10.3389/fnhum.2014.00444  24994978.0  ...     5.445466   
...                             ...         ...  ...          ...   
1582                            NaN  11252267.0  ...     0.055891   
1583       10.3390/brainsci12111552  36421877.0  ...     0.000000   
1584       10.1177/1088868313495594  23861355.0  ...     3.958603   
1585  10.3233/978-1-60750-583-9-112  20543431.0  ...     0.737614   
1586              10.1063/1.4948985         NaN  ...     0.059848   

     fncr_all_years                                         hc_3_years  \
32         1.706871  {"(\"Computer Science, Interdisciplinary Appli...   
177        0.000000  {"(Neurosciences,0.0)","(Physiology,0.0)","(Bi...   
215        0.000000  {"(\"Computer Science, Artificial Intelligence...   
265        0.050769  {"(\"Computer Science, Artificial Intelligence...   
277        6.641124         {"(Psychology,1.0)","(Neurosciences,1.0)"}   
...             ...                                                ...   
1582       0.048093  {"(Physiology,0.0)","(Biophysics,0.0)","(Bioch...   
1583       0.000000       

In [7]:
dup_counts = cn_full.groupby('title_lower').size().reset_index(name='count')

# Filter rows where count > 1 to get duplicates
dup_overview = dup_counts[dup_counts['count'] > 1].sort_values(by='count', ascending=False)

dup_overview

title_lower  count
151   a subsequent closed-form description of propag...      2
1210  reorganization of the human cns - neurophysiol...      2
953   modelling honeybee visual guidance in a 3-d en...      2
976   multi-site voxel-based morphometry - not quite...      2
1037  neuronal circuit-based computer modeling as a ...      2
1042  neuronal reorganization through oscillator for...      2
1049  neuroplasticity and the brain connectome: what...      2
1057  noise in a randomly and sparsely connected exc...      2
1219  resolving the biophysics of axon transmembrane...      2
815   integrating fmri and single-cell data of visua...      2
1293  spikenet: real-time visual processing with one...      2
1296       spiking neuron model approximation using gep      2
1326  structures in physics and neuroscience structu...      2
1415  the portuguese bing network: towards a brain i...      2
1431     the three cultures of computational psychiatry      2
1462  toward a new cognitive neuroscience: modeling ...      2
830   introduction to machine learning for brain ima...      2
789   improved izhikevich neurons for spiking neural...      2
175   action, outcome, and value: a dual-system fram...      2
451                   computational physics of the mind      2
191   age is not necessarily aging: another step tow...      2
228   analysis of eeg frequency bands during typical...      2
287               bayesian brain: can we model emotion?      2
300   beyond traditional approaches to understanding...      2
315    biomedical wellness challenges and opportunities      2
352   can videogames improve executive functioning? ...      2
452                            computational psychiatry      2
768   human-scale brain simulation via supercomputer...      2
485   correlation between videogame mechanics and ex...      2
486   cortical basis of communication: local computa...      2
553   dynamical complexity in cognitive neural networks      2
569   editorial: hierarchical object representations...      2
607   episodix: a serious game to detect cognitive i...      2
734   grid-wide neuroimaging data federation in the ...      2
1525  virtual intelligence: a systematic review of t...      2

Check for generic titles that could in fact be different publications instead of only duplicates

In [8]:
#cn_full[cn_full['title_lower'] == 'computational psychiatry'] # different articles!!
#cn_full[cn_full['title_lower'] == 'computational physics of the mind'] # same article
#cn_full[cn_full['title_lower'] == 'dynamical complexity in cognitive neural networks'] # same article
#cn_full[cn_full['title_lower'] == 'introduction to machine learning for brain imaging'] # same article


Removal of all duplicate titles except the ones with the title "computational psychiatry"

In [9]:
# Find rows with 'title_lower' as "computational psychiatry" and remove duplicates while always keeping the first occurrence
comppsy = cn_full[cn_full['title_lower'] == 'computational psychiatry']
filtered_cn_full = cn_full[(cn_full['title_lower'] != 'computational psychiatry')].drop_duplicates(subset='title_lower', keep='first') # Exclude rows with 'title_lower' as "computational psychiatry"!

# "Remerge" the filtered df and the "computational psychiatry" rows
cn_full = pd.concat([filtered_cn_full, comppsy]).sort_index()

cn_full.shape # (1553, 52)

(1553, 52)

In [11]:
# Save clean data to csv
cn_full.to_csv('cn_items_clean.csv', index=False)

list_item_ids = cn_full['item_id'].tolist()
with open('list_item_ids.txt', 'w') as file: # "Context manager" saves item ids to txt file
    for item in list_item_ids:
        file.write(str(item) + '\n')

# Save item ids to csv for sql data base search of references
item_ids_df = pd.DataFrame(list_item_ids, columns=['item_id'])
item_ids_df.to_csv('item_ids.csv', index=False)


In [ ]:
# Convert list to comma-separated string with quoted values for the KB sql query of references
wos_ids = ', '.join(f"'{id_}'" for id_ in list_item_ids)
#print(wos_ids)


After checking for duplicates, we can assume to have a clean dataset with 1553 articles. We can now start with the preliminary analysis.